services:
  - type: web
    name: tiger-farmer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tiger_farmer.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.10.0
